// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT5LOt_GgCC1ACvTnNB_ylVfcOVD78j6M',
    appId: '1:432865955205:android:bafa8df2d5d968ecaf48ec',
    messagingSenderId: '432865955205',
    projectId: 'readpro-c466c',
    storageBucket: 'readpro-c466c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4hpljrAVJ_rhRUzSYdV83HDe7wLYz0Y',
    appId: '1:432865955205:ios:cf03bc0bba13b7b6af48ec',
    messagingSenderId: '432865955205',
    projectId: 'readpro-c466c',
    storageBucket: 'readpro-c466c.firebasestorage.app',
    androidClientId: '432865955205-36u7is9vuflne5uf1a0egflathr3unse.apps.googleusercontent.com',
    iosClientId: '432865955205-j99jlqcgtj2l2b9bk65sv4g1pfqi5pa8.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendenceApp',
  );
}
