// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD40zPl0vQLeBpWEE-2nrDNUt30DA0os3s',
    appId: '1:612154567444:android:d1f666bdd7014a7393b001',
    messagingSenderId: '612154567444',
    projectId: 'webchat-d646a',
    databaseURL: 'https://webchat-d646a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webchat-d646a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaaBc_mY4EJsd6cDZAKgU17F3eoR7MPQA',
    appId: '1:612154567444:ios:8bcada5d17740b6393b001',
    messagingSenderId: '612154567444',
    projectId: 'webchat-d646a',
    databaseURL: 'https://webchat-d646a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'webchat-d646a.appspot.com',
    iosBundleId: 'com.example.attendenceApp',
  );

}